### ISSUE TITLE
In ambient enum declarations member initializer must be constant expression.

### ISSUE THREAD

**Issue by aslate** [tpluscode/jsonld-typings#1]
Hey,

Not sure if this is an issue with typescript, typings or jsonld-typings but I'm getting the following error after installing jsonld as a non-ambient dependency:

```
ERROR in typings/browser/definitions/jsonld/index.d.ts
(142,15): error TS1066: In ambient enum declarations member initializer must be constant expression.
```

In an attempt to resolve this I tried ambient mode anyway, but it doesn't install

```
typings ERR! message Attempted to compile "jsonld" as an ambient module, but it looks like an external module.
```

Using typings 0.8.1 and tsc 1.8.10

**Comment by tpluscode** [comment]
These typings shouldn't be installed as ambient. 

I think I'm using the enum incorrectly. Please try changing the `enum EmbedEnum` to

```
type EmbedEnum = '@last' |  '@always' | '@never' | '@link';
```

**Comment by aslate** [comment]
I haven't installed them as ambient - I just decided to try it and it made no difference. My typings.json looks like:

```
  "ambientDependencies": { ... },
  "dependencies": {
    "jsonld": "registry:npm/jsonld#0.4.0+20160423203356"
  }
```

Your recommended fix does the trick though.

**Comment by tpluscode** [comment]
Thanks. I've submitted a pull request to typings/registry#389. Please update with `typings` command when it's merged
